// This file is generated by packages/site/scripts/generate-docs.mjs.
// Do not edit by hand.

export type GeneratedDocBlock =
  | { type: 'heading'; level: number; text: string }
  | { type: 'paragraph'; text: string }
  | { type: 'code'; lang: string; code: string }
  | { type: 'list'; items: string[] }
  | { type: 'table'; headers: string[]; rows: string[][] }

export interface GeneratedPackageDoc {
  id: string
  name: string
  version: string
  description: string
  install: string
  source: string
  readmeUrl: string
  blocks: GeneratedDocBlock[]
}

export type GeneratedLocale = ["zh-CN","en"][number]

export const generatedDocsByLocale = {
  "zh-CN": [
    {
      "id": "web",
      "name": "@uicheck/web",
      "version": "0.1.8",
      "description": "浏览器 DOM 页面客户端",
      "install": "npm install @uicheck/web",
      "source": "packages/web",
      "readmeUrl": "https://github.com/uicheck/uicheck/blob/main/packages/web/README.zh-CN.md",
      "blocks": [
        {
          "type": "paragraph",
          "text": "浏览器运行环境客户端。它通过 WebSocket 把真实 DOM 页面连接到 @uicheck/mcp，让 AI 可以通过 MCP 工具读取截图、元素元数据、布局盒和坐标。"
        },
        {
          "type": "heading",
          "level": 2,
          "text": "使用"
        },
        {
          "type": "code",
          "lang": "ts",
          "code": "import { initUiCheck } from '@uicheck/web'\n\ninitUiCheck({\n  socket: {\n    url: 'ws://127.0.0.1:17322/socket'\n  }\n})"
        },
        {
          "type": "heading",
          "level": 2,
          "text": "选项"
        },
        {
          "type": "table",
          "headers": [
            "选项",
            "类型",
            "默认值",
            "说明"
          ],
          "rows": [
            [
              "socket.url",
              "string",
              "-",
              "@uicheck/mcp WebSocket 地址"
            ],
            [
              "socket.clientId",
              "string",
              "-",
              "可选的稳定客户端 ID"
            ],
            [
              "socket.reconnectMs",
              "number",
              "1000",
              "断线重连间隔"
            ]
          ]
        }
      ]
    },
    {
      "id": "taro",
      "name": "@uicheck/taro",
      "version": "0.1.8",
      "description": "Taro 小程序页面客户端",
      "install": "npm install @uicheck/taro",
      "source": "packages/taro",
      "readmeUrl": "https://github.com/uicheck/uicheck/blob/main/packages/taro/README.zh-CN.md",
      "blocks": [
        {
          "type": "paragraph",
          "text": "Taro 小程序侧 UI 检查客户端。它通过小程序 selector query 读取页面元素，并连接 @uicheck/mcp 给 AI 提供结构化 UI 信息。"
        },
        {
          "type": "code",
          "lang": "ts",
          "code": "import { initUiCheck } from '@uicheck/taro'\n\ninitUiCheck({\n  socket: {\n    url: 'ws://127.0.0.1:17322/socket'\n  }\n})"
        },
        {
          "type": "heading",
          "level": 2,
          "text": "选项"
        },
        {
          "type": "table",
          "headers": [
            "选项",
            "类型",
            "默认值",
            "说明"
          ],
          "rows": [
            [
              "socket.url",
              "string",
              "-",
              "@uicheck/mcp WebSocket 地址"
            ],
            [
              "socket.clientId",
              "string",
              "-",
              "可选的稳定客户端 ID"
            ],
            [
              "socket.reconnectMs",
              "number",
              "1000",
              "断线重连间隔"
            ],
            [
              "screenshot",
              "function",
              "-",
              "可选截图函数，返回 PNG base64"
            ]
          ]
        }
      ]
    },
    {
      "id": "rn",
      "name": "@uicheck/rn",
      "version": "0.1.8",
      "description": "React Native 页面客户端",
      "install": "npm install @uicheck/rn",
      "source": "packages/rn",
      "readmeUrl": "https://github.com/uicheck/uicheck/blob/main/packages/rn/README.zh-CN.md",
      "blocks": [
        {
          "type": "paragraph",
          "text": "React Native 客户端。initUiCheck 会在安装时接入 React / JSX 创建流程，让 AI 通过 @uicheck/mcp 读取真实运行时元素的布局、文本、testID 和无障碍标签。"
        },
        {
          "type": "code",
          "lang": "ts",
          "code": "import { initUiCheck } from '@uicheck/rn'\n\ninitUiCheck({\n  socket: {\n    url: 'ws://127.0.0.1:17322/socket'\n  }\n})"
        },
        {
          "type": "heading",
          "level": 2,
          "text": "截图"
        },
        {
          "type": "paragraph",
          "text": "React Native 截图依赖宿主应用。需要支持 capture_page 时传入返回 PNG base64 的 screenshot 函数。"
        },
        {
          "type": "code",
          "lang": "ts",
          "code": "initUiCheck({\n  screenshot: async () => ({\n    mimeType: 'image/png',\n    base64: await captureAppAsBase64()\n  })\n})"
        },
        {
          "type": "heading",
          "level": 2,
          "text": "选项"
        },
        {
          "type": "table",
          "headers": [
            "选项",
            "类型",
            "默认值",
            "说明"
          ],
          "rows": [
            [
              "socket.url",
              "string",
              "-",
              "@uicheck/mcp WebSocket 地址"
            ],
            [
              "socket.clientId",
              "string",
              "-",
              "可选的稳定客户端 ID"
            ],
            [
              "socket.reconnectMs",
              "number",
              "1000",
              "断线重连间隔"
            ],
            [
              "screenshot",
              "function",
              "-",
              "可选截图函数，返回 PNG base64"
            ]
          ]
        }
      ]
    },
    {
      "id": "flutter",
      "name": "uicheck_flutter",
      "version": "0.1.8",
      "description": "Flutter 应用运行环境客户端",
      "install": "flutter pub add uicheck_flutter",
      "source": "packages/flutter",
      "readmeUrl": "https://github.com/uicheck/uicheck/blob/main/packages/flutter/README.zh-CN.md",
      "blocks": [
        {
          "type": "paragraph",
          "text": "Flutter 运行时客户端。它把真实 Flutter 应用通过 WebSocket 接到 @uicheck/mcp，让 AI 请求截图并检查 Flutter render tree。"
        },
        {
          "type": "heading",
          "level": 2,
          "text": "使用"
        },
        {
          "type": "paragraph",
          "text": "添加依赖："
        },
        {
          "type": "code",
          "lang": "sh",
          "code": "flutter pub add uicheck_flutter"
        },
        {
          "type": "paragraph",
          "text": "单独启动 MCP 服务："
        },
        {
          "type": "code",
          "lang": "sh",
          "code": "npx @uicheck/mcp"
        },
        {
          "type": "paragraph",
          "text": "在应用启动时安装客户端："
        },
        {
          "type": "code",
          "lang": "dart",
          "code": "import 'package:flutter/widgets.dart';\nimport 'package:uicheck_flutter/uicheck_flutter.dart';\n\nfinal uicheckClient = initUiCheck(\n  UiCheckFlutterOptions(\n    socket: UiCheckSocketOptions(\n      clientId: 'flutter-demo',\n    ),\n    screenshot: (params) => captureRepaintBoundaryAsPng(\n      repaintBoundaryKey: appBoundaryKey,\n    ),\n  ),\n);"
        },
        {
          "type": "paragraph",
          "text": "使用截图 helper 时，把应用或页面包在 RepaintBoundary 里："
        },
        {
          "type": "code",
          "lang": "dart",
          "code": "final appBoundaryKey = GlobalKey();\n\nRepaintBoundary(\n  key: appBoundaryKey,\n  child: MyApp(),\n);"
        },
        {
          "type": "paragraph",
          "text": "不再需要时释放客户端："
        },
        {
          "type": "code",
          "lang": "dart",
          "code": "uicheckClient.dispose();"
        },
        {
          "type": "heading",
          "level": 2,
          "text": "选项"
        },
        {
          "type": "table",
          "headers": [
            "选项",
            "类型",
            "默认值",
            "说明"
          ],
          "rows": [
            [
              "socket.url",
              "String",
              "-",
              "@uicheck/mcp WebSocket 地址"
            ],
            [
              "socket.clientId",
              "String",
              "-",
              "可选的稳定客户端 ID"
            ],
            [
              "socket.reconnectMs",
              "int",
              "1000",
              "断线重连间隔"
            ],
            [
              "screenshot",
              "UiCheckScreenshotProvider",
              "-",
              "可选截图函数，返回 PNG base64"
            ]
          ]
        }
      ]
    },
    {
      "id": "android",
      "name": "uicheck_android",
      "version": "0.1.8",
      "description": "Android 原生应用运行环境客户端",
      "install": "Android library: https://github.com/uicheck/uicheck, path packages/android",
      "source": "packages/android",
      "readmeUrl": "https://github.com/uicheck/uicheck/blob/main/packages/android/README.zh-CN.md",
      "blocks": [
        {
          "type": "paragraph",
          "text": "Android 原生运行时客户端。它把真实 Android 应用通过 WebSocket 接到 @uicheck/mcp，让 AI 请求截图并检查 Android view tree。"
        },
        {
          "type": "heading",
          "level": 2,
          "text": "安装"
        },
        {
          "type": "paragraph",
          "text": "把这个仓库作为 Android library 依赖添加："
        },
        {
          "type": "code",
          "lang": "txt",
          "code": "https://github.com/uicheck/uicheck"
        },
        {
          "type": "paragraph",
          "text": "包路径："
        },
        {
          "type": "code",
          "lang": "txt",
          "code": "packages/android"
        },
        {
          "type": "paragraph",
          "text": "单独启动 MCP 服务："
        },
        {
          "type": "code",
          "lang": "sh",
          "code": "npx @uicheck/mcp"
        },
        {
          "type": "heading",
          "level": 2,
          "text": "使用"
        },
        {
          "type": "paragraph",
          "text": "在应用启动时安装客户端："
        },
        {
          "type": "code",
          "lang": "kotlin",
          "code": "import ai.uicheck.android.UiCheckAndroidOptions\nimport ai.uicheck.android.UiCheckAndroidSocketOptions\nimport ai.uicheck.android.initUiCheck\n\nval client = initUiCheck(\n  UiCheckAndroidOptions(\n    socket = UiCheckAndroidSocketOptions(\n      url = \"ws://127.0.0.1:17322/socket\",\n      clientId = \"android-demo\"\n    ),\n    activity = this\n  )\n)"
        },
        {
          "type": "paragraph",
          "text": "不再需要时释放："
        },
        {
          "type": "code",
          "lang": "kotlin",
          "code": "client.close()"
        },
        {
          "type": "heading",
          "level": 2,
          "text": "选项"
        },
        {
          "type": "table",
          "headers": [
            "选项",
            "类型",
            "默认值",
            "说明"
          ],
          "rows": [
            [
              "socket.url",
              "String",
              "-",
              "@uicheck/mcp WebSocket 地址"
            ],
            [
              "socket.clientId",
              "String",
              "-",
              "可选的稳定客户端 ID"
            ],
            [
              "socket.reconnectMs",
              "Long",
              "1000",
              "断线重连间隔"
            ],
            [
              "activity",
              "Activity",
              "-",
              "当前 Activity，用来自动读取根 View 和截图"
            ],
            [
              "screenshot",
              "function",
              "-",
              "可选截图 provider，返回 PNG base64"
            ]
          ]
        }
      ]
    },
    {
      "id": "apple",
      "name": "uicheck_apple",
      "version": "0.1.8",
      "description": "Apple 原生应用运行环境客户端",
      "install": "Swift Package: https://github.com/uicheck/uicheck, product UICheckApple",
      "source": "packages/apple",
      "readmeUrl": "https://github.com/uicheck/uicheck/blob/main/packages/apple/README.zh-CN.md",
      "blocks": [
        {
          "type": "paragraph",
          "text": "Apple 原生运行时客户端。它把 iOS、macOS、tvOS 或 visionOS 应用通过 WebSocket 接到 @uicheck/mcp，让 AI 请求截图并检查 UIKit/AppKit view tree。"
        },
        {
          "type": "heading",
          "level": 2,
          "text": "安装"
        },
        {
          "type": "paragraph",
          "text": "把这个仓库作为 Swift Package 依赖添加，并选择 UICheckApple product："
        },
        {
          "type": "code",
          "lang": "txt",
          "code": "https://github.com/uicheck/uicheck"
        },
        {
          "type": "paragraph",
          "text": "包路径："
        },
        {
          "type": "code",
          "lang": "txt",
          "code": "packages/apple"
        },
        {
          "type": "paragraph",
          "text": "单独启动 MCP 服务："
        },
        {
          "type": "code",
          "lang": "sh",
          "code": "npx @uicheck/mcp"
        },
        {
          "type": "heading",
          "level": 2,
          "text": "使用"
        },
        {
          "type": "paragraph",
          "text": "在应用启动时安装客户端："
        },
        {
          "type": "code",
          "lang": "swift",
          "code": "import UICheckApple\n\nlet client = initUiCheck(\n  UiCheckAppleOptions(\n    socket: UiCheckAppleSocketOptions(\n      clientId: \"ios-demo\"\n    ),\n    screenshot: { params in\n      UiCheckAppleScreenshotResult(\n        width: 390,\n        height: 844,\n        mimeType: \"image/png\",\n        base64: captureAppAsBase64Png()\n      )\n    }\n  )\n)"
        },
        {
          "type": "paragraph",
          "text": "不再需要时释放："
        },
        {
          "type": "code",
          "lang": "swift",
          "code": "client.close()"
        },
        {
          "type": "heading",
          "level": 2,
          "text": "选项"
        },
        {
          "type": "table",
          "headers": [
            "选项",
            "类型",
            "默认值",
            "说明"
          ],
          "rows": [
            [
              "socket.url",
              "String",
              "-",
              "@uicheck/mcp WebSocket 地址"
            ],
            [
              "socket.clientId",
              "String",
              "-",
              "可选的稳定客户端 ID"
            ],
            [
              "socket.reconnectMs",
              "Int",
              "1000",
              "断线重连间隔"
            ],
            [
              "screenshot",
              "function",
              "-",
              "可选截图函数，返回 PNG base64"
            ]
          ]
        }
      ]
    },
    {
      "id": "mcp",
      "name": "@uicheck/mcp",
      "version": "0.1.8",
      "description": "通过 WebSocket 连接 uicheck 客户端的 MCP 服务",
      "install": "npx @uicheck/mcp",
      "source": "packages/mcp",
      "readmeUrl": "https://github.com/uicheck/uicheck/blob/main/packages/mcp/README.zh-CN.md",
      "blocks": [
        {
          "type": "paragraph",
          "text": "本地 MCP 服务，用于通过 WebSocket 连接 uicheck 运行环境客户端。Web、Taro 小程序、React Native、Flutter、Apple 原生或 Android 原生应用连接后，AI 可以调用 MCP 工具请求截图和树状元素信息。"
        },
        {
          "type": "heading",
          "level": 2,
          "text": "启动"
        },
        {
          "type": "code",
          "lang": "sh",
          "code": "npx @uicheck/mcp"
        },
        {
          "type": "paragraph",
          "text": "默认端点："
        },
        {
          "type": "code",
          "lang": "txt",
          "code": "MCP:    http://127.0.0.1:17322/mcp\nSocket: ws://127.0.0.1:17322/socket"
        },
        {
          "type": "heading",
          "level": 2,
          "text": "AI 客户端配置"
        },
        {
          "type": "paragraph",
          "text": "把 MCP endpoint 配到任意支持 MCP 的 AI 客户端："
        },
        {
          "type": "code",
          "lang": "json",
          "code": "{\n  \"mcpServers\": {\n    \"uicheck\": {\n      \"url\": \"http://127.0.0.1:17322/mcp\"\n    }\n  }\n}"
        },
        {
          "type": "heading",
          "level": 2,
          "text": "运行环境客户端"
        },
        {
          "type": "paragraph",
          "text": "应用运行环境连接 socket 地址。浏览器页面使用 @uicheck/web："
        },
        {
          "type": "code",
          "lang": "ts",
          "code": "initUiCheck({\n  socket: {\n    url: 'ws://127.0.0.1:17322/socket'\n  }\n})"
        },
        {
          "type": "paragraph",
          "text": "Taro 小程序使用 @uicheck/taro，React Native 使用 @uicheck/rn，Flutter 使用 uicheck_flutter，Apple 原生使用 uicheck_apple，Android 原生使用 uicheck_android。"
        },
        {
          "type": "heading",
          "level": 2,
          "text": "MCP 工具"
        },
        {
          "type": "table",
          "headers": [
            "工具",
            "说明",
            "参数",
            "返回"
          ],
          "rows": [
            [
              "list_clients",
              "查看已连接的 uicheck 运行环境客户端。",
              "无",
              "JSON 文本数组。每项包含 id、connectedAt、lastSeenAt，以及可选的 userAgent、viewport。"
            ],
            [
              "capture_page",
              "请求已连接运行环境返回 PNG 截图。",
              "clientId 可选目标客户端 ID；timeoutMs MCP 等待超时；waitMs 截图前等待时间；captureTimeoutMs 运行环境截图超时；forceHtml2Canvas 强制 Web 端使用 html2canvas。",
              "MCP image 内容，mimeType 为 image/png；附带 JSON 文本 { width, height }。"
            ],
            [
              "capture_element",
              "截取第一个命中查询条件的元素 PNG 图。",
              "与 capture_page 相同的截图参数；额外支持 includeHidden、query、selector、styleName 加可选 styleValue、styles、id、testId、text、accessibilityLabel、className、role、tag。",
              "MCP image 内容，mimeType 为 image/png；附带 JSON 文本 { width, height }。"
            ],
            [
              "compare_screenshot",
              "截取当前页面或命中元素，并和传入的 PNG 图片做像素对比。",
              "与 capture_element 相同的截图和查询参数；target 可为 page 或 element，默认 page；expectedImageBase64 必填；threshold 为 pixelmatch 阈值。",
              "JSON 文本，包含 width、height、mismatchedPixels、totalPixels、mismatchRatio、passed；附带 PNG diff 图。"
            ],
            [
              "inspect_elements",
              "返回树状节点、文本、布局盒和元数据。传入查找参数时，只保留命中节点和它的父级树。",
              "clientId 可选目标客户端 ID；timeoutMs MCP 等待超时；limit 最大节点数，默认 80；includeHidden 是否包含隐藏或零尺寸节点；query 搜索常见节点字段；selector、styleName 加可选 styleValue、styles、id、testId、text、accessibilityLabel、className、role、tag 用于缩小匹配范围。",
              "JSON 文本。包含 count 和树状 tree，节点包含文本、可见性、布局盒、测试 ID、无障碍标签、类名和子节点等运行环境可提供的信息。"
            ]
          ]
        },
        {
          "type": "heading",
          "level": 2,
          "text": "CLI"
        },
        {
          "type": "code",
          "lang": "sh",
          "code": "npx @uicheck/mcp -- --host 127.0.0.1 --port 17322"
        }
      ]
    }
  ],
  "en": [
    {
      "id": "web",
      "name": "@uicheck/web",
      "version": "0.1.8",
      "description": "Browser DOM client for uicheck",
      "install": "npm install @uicheck/web",
      "source": "packages/web",
      "readmeUrl": "https://github.com/uicheck/uicheck/blob/main/packages/web/README.md",
      "blocks": [
        {
          "type": "paragraph",
          "text": "Browser runtime client for UI Check. It connects a live DOM page to @uicheck/mcp over WebSocket so AI agents can request screenshots, element metadata, layout boxes through MCP tools."
        },
        {
          "type": "heading",
          "level": 2,
          "text": "Usage"
        },
        {
          "type": "code",
          "lang": "ts",
          "code": "import { initUiCheck } from '@uicheck/web'\n\ninitUiCheck({\n  socket: {\n    url: 'ws://127.0.0.1:17322/socket'\n  }\n})"
        },
        {
          "type": "heading",
          "level": 2,
          "text": "Options"
        },
        {
          "type": "table",
          "headers": [
            "Option",
            "Type",
            "Default",
            "Description"
          ],
          "rows": [
            [
              "socket.url",
              "string",
              "-",
              "@uicheck/mcp WebSocket URL"
            ],
            [
              "socket.clientId",
              "string",
              "-",
              "Optional stable client id"
            ],
            [
              "socket.reconnectMs",
              "number",
              "1000",
              "Reconnect interval"
            ]
          ]
        }
      ]
    },
    {
      "id": "taro",
      "name": "@uicheck/taro",
      "version": "0.1.8",
      "description": "Taro Mini Program client for uicheck",
      "install": "npm install @uicheck/taro",
      "source": "packages/taro",
      "readmeUrl": "https://github.com/uicheck/uicheck/blob/main/packages/taro/README.md",
      "blocks": [
        {
          "type": "paragraph",
          "text": "Taro Mini Program client for uicheck."
        },
        {
          "type": "code",
          "lang": "ts",
          "code": "import { initUiCheck } from '@uicheck/taro'\n\ninitUiCheck({\n  socket: {\n    url: 'ws://127.0.0.1:17322/socket'\n  }\n})"
        },
        {
          "type": "heading",
          "level": 2,
          "text": "Options"
        },
        {
          "type": "table",
          "headers": [
            "Option",
            "Type",
            "Default",
            "Description"
          ],
          "rows": [
            [
              "socket.url",
              "string",
              "-",
              "@uicheck/mcp WebSocket URL"
            ],
            [
              "socket.clientId",
              "string",
              "-",
              "Optional stable client id"
            ],
            [
              "socket.reconnectMs",
              "number",
              "1000",
              "Reconnect interval"
            ],
            [
              "screenshot",
              "function",
              "-",
              "Optional screenshot function that returns PNG base64"
            ]
          ]
        }
      ]
    },
    {
      "id": "rn",
      "name": "@uicheck/rn",
      "version": "0.1.8",
      "description": "React Native client for uicheck",
      "install": "npm install @uicheck/rn",
      "source": "packages/rn",
      "readmeUrl": "https://github.com/uicheck/uicheck/blob/main/packages/rn/README.md",
      "blocks": [
        {
          "type": "paragraph",
          "text": "React Native client for uicheck. It instruments React / JSX creation during initUiCheck so AI agents can inspect runtime element boxes, text, testID, and accessibility labels through @uicheck/mcp."
        },
        {
          "type": "code",
          "lang": "ts",
          "code": "import { initUiCheck } from '@uicheck/rn'\n\ninitUiCheck({\n  socket: {\n    url: 'ws://127.0.0.1:17322/socket'\n  }\n})"
        },
        {
          "type": "heading",
          "level": 2,
          "text": "Screenshot"
        },
        {
          "type": "paragraph",
          "text": "React Native screenshots depend on the host app. To support capture_page, pass a screenshot function that returns PNG base64."
        },
        {
          "type": "code",
          "lang": "ts",
          "code": "initUiCheck({\n  screenshot: async () => ({\n    mimeType: 'image/png',\n    base64: await captureAppAsBase64()\n  })\n})"
        },
        {
          "type": "heading",
          "level": 2,
          "text": "Options"
        },
        {
          "type": "table",
          "headers": [
            "Option",
            "Type",
            "Default",
            "Description"
          ],
          "rows": [
            [
              "socket.url",
              "string",
              "-",
              "@uicheck/mcp WebSocket URL"
            ],
            [
              "socket.clientId",
              "string",
              "-",
              "Optional stable client id"
            ],
            [
              "socket.reconnectMs",
              "number",
              "1000",
              "Reconnect interval"
            ],
            [
              "screenshot",
              "function",
              "-",
              "Optional screenshot function that returns PNG base64"
            ]
          ]
        }
      ]
    },
    {
      "id": "flutter",
      "name": "uicheck_flutter",
      "version": "0.1.8",
      "description": "Flutter runtime client for uicheck",
      "install": "flutter pub add uicheck_flutter",
      "source": "packages/flutter",
      "readmeUrl": "https://github.com/uicheck/uicheck/blob/main/packages/flutter/README.md",
      "blocks": [
        {
          "type": "paragraph",
          "text": "Flutter runtime client for UI Check. It connects a running Flutter app to @uicheck/mcp over WebSocket so AI agents can request screenshots and inspect the live Flutter render tree."
        },
        {
          "type": "heading",
          "level": 2,
          "text": "Usage"
        },
        {
          "type": "paragraph",
          "text": "Add the package:"
        },
        {
          "type": "code",
          "lang": "sh",
          "code": "flutter pub add uicheck_flutter"
        },
        {
          "type": "paragraph",
          "text": "Start the MCP server separately:"
        },
        {
          "type": "code",
          "lang": "sh",
          "code": "npx @uicheck/mcp"
        },
        {
          "type": "paragraph",
          "text": "Install the Flutter client near app startup:"
        },
        {
          "type": "code",
          "lang": "dart",
          "code": "import 'package:flutter/widgets.dart';\nimport 'package:uicheck_flutter/uicheck_flutter.dart';\n\nfinal uicheckClient = initUiCheck(\n  UiCheckFlutterOptions(\n    socket: UiCheckSocketOptions(\n      clientId: 'flutter-demo',\n    ),\n    screenshot: (params) => captureRepaintBoundaryAsPng(\n      repaintBoundaryKey: appBoundaryKey,\n    ),\n  ),\n);"
        },
        {
          "type": "paragraph",
          "text": "Wrap the app or screen in a RepaintBoundary when using the screenshot helper:"
        },
        {
          "type": "code",
          "lang": "dart",
          "code": "final appBoundaryKey = GlobalKey();\n\nRepaintBoundary(\n  key: appBoundaryKey,\n  child: MyApp(),\n);"
        },
        {
          "type": "paragraph",
          "text": "Dispose the client when it is no longer needed:"
        },
        {
          "type": "code",
          "lang": "dart",
          "code": "uicheckClient.dispose();"
        },
        {
          "type": "heading",
          "level": 2,
          "text": "Options"
        },
        {
          "type": "table",
          "headers": [
            "Option",
            "Type",
            "Default",
            "Description"
          ],
          "rows": [
            [
              "socket.url",
              "String",
              "-",
              "@uicheck/mcp WebSocket URL"
            ],
            [
              "socket.clientId",
              "String",
              "-",
              "Optional stable client id"
            ],
            [
              "socket.reconnectMs",
              "int",
              "1000",
              "Reconnect interval"
            ],
            [
              "screenshot",
              "UiCheckScreenshotProvider",
              "-",
              "Optional screenshot function that returns PNG base64"
            ]
          ]
        }
      ]
    },
    {
      "id": "android",
      "name": "uicheck_android",
      "version": "0.1.8",
      "description": "Android native runtime client for uicheck",
      "install": "Android library: https://github.com/uicheck/uicheck, path packages/android",
      "source": "packages/android",
      "readmeUrl": "https://github.com/uicheck/uicheck/blob/main/packages/android/README.md",
      "blocks": [
        {
          "type": "paragraph",
          "text": "Android native runtime client for UI Check. It connects native Android apps to @uicheck/mcp over WebSocket so AI agents can request screenshots and inspect the live Android view tree."
        },
        {
          "type": "heading",
          "level": 2,
          "text": "Install"
        },
        {
          "type": "paragraph",
          "text": "Add this repository as an Android library dependency:"
        },
        {
          "type": "code",
          "lang": "txt",
          "code": "https://github.com/uicheck/uicheck"
        },
        {
          "type": "paragraph",
          "text": "Package path:"
        },
        {
          "type": "code",
          "lang": "txt",
          "code": "packages/android"
        },
        {
          "type": "paragraph",
          "text": "Start the MCP server separately:"
        },
        {
          "type": "code",
          "lang": "sh",
          "code": "npx @uicheck/mcp"
        },
        {
          "type": "heading",
          "level": 2,
          "text": "Usage"
        },
        {
          "type": "paragraph",
          "text": "Install the client near app startup:"
        },
        {
          "type": "code",
          "lang": "kotlin",
          "code": "import ai.uicheck.android.UiCheckAndroidOptions\nimport ai.uicheck.android.UiCheckAndroidSocketOptions\nimport ai.uicheck.android.initUiCheck\n\nval client = initUiCheck(\n  UiCheckAndroidOptions(\n    socket = UiCheckAndroidSocketOptions(\n      url = \"ws://127.0.0.1:17322/socket\",\n      clientId = \"android-demo\"\n    ),\n    activity = this\n  )\n)"
        },
        {
          "type": "paragraph",
          "text": "Dispose when no longer needed:"
        },
        {
          "type": "code",
          "lang": "kotlin",
          "code": "client.close()"
        },
        {
          "type": "heading",
          "level": 2,
          "text": "Options"
        },
        {
          "type": "table",
          "headers": [
            "Option",
            "Type",
            "Default",
            "Description"
          ],
          "rows": [
            [
              "socket.url",
              "String",
              "-",
              "@uicheck/mcp WebSocket URL"
            ],
            [
              "socket.clientId",
              "String",
              "-",
              "Optional stable client id"
            ],
            [
              "socket.reconnectMs",
              "Long",
              "1000",
              "Reconnect interval"
            ],
            [
              "activity",
              "Activity",
              "-",
              "Current Activity used to read the root View and capture screenshots"
            ],
            [
              "screenshot",
              "function",
              "-",
              "Optional screenshot provider that returns PNG base64"
            ]
          ]
        }
      ]
    },
    {
      "id": "apple",
      "name": "uicheck_apple",
      "version": "0.1.8",
      "description": "Apple native runtime client for uicheck",
      "install": "Swift Package: https://github.com/uicheck/uicheck, product UICheckApple",
      "source": "packages/apple",
      "readmeUrl": "https://github.com/uicheck/uicheck/blob/main/packages/apple/README.md",
      "blocks": [
        {
          "type": "paragraph",
          "text": "Apple native runtime client for UI Check. It connects iOS, macOS, tvOS, or visionOS apps to @uicheck/mcp over WebSocket so AI agents can request screenshots and inspect the live UIKit/AppKit view tree."
        },
        {
          "type": "heading",
          "level": 2,
          "text": "Install"
        },
        {
          "type": "paragraph",
          "text": "Add this repository as a Swift Package dependency and select the UICheckApple product:"
        },
        {
          "type": "code",
          "lang": "txt",
          "code": "https://github.com/uicheck/uicheck"
        },
        {
          "type": "paragraph",
          "text": "Package path:"
        },
        {
          "type": "code",
          "lang": "txt",
          "code": "packages/apple"
        },
        {
          "type": "paragraph",
          "text": "Start the MCP server separately:"
        },
        {
          "type": "code",
          "lang": "sh",
          "code": "npx @uicheck/mcp"
        },
        {
          "type": "heading",
          "level": 2,
          "text": "Usage"
        },
        {
          "type": "paragraph",
          "text": "Install the client near app startup:"
        },
        {
          "type": "code",
          "lang": "swift",
          "code": "import UICheckApple\n\nlet client = initUiCheck(\n  UiCheckAppleOptions(\n    socket: UiCheckAppleSocketOptions(\n      clientId: \"ios-demo\"\n    ),\n    screenshot: { params in\n      UiCheckAppleScreenshotResult(\n        width: 390,\n        height: 844,\n        mimeType: \"image/png\",\n        base64: captureAppAsBase64Png()\n      )\n    }\n  )\n)"
        },
        {
          "type": "paragraph",
          "text": "Dispose when no longer needed:"
        },
        {
          "type": "code",
          "lang": "swift",
          "code": "client.close()"
        },
        {
          "type": "heading",
          "level": 2,
          "text": "Options"
        },
        {
          "type": "table",
          "headers": [
            "Option",
            "Type",
            "Default",
            "Description"
          ],
          "rows": [
            [
              "socket.url",
              "String",
              "-",
              "@uicheck/mcp WebSocket URL"
            ],
            [
              "socket.clientId",
              "String",
              "-",
              "Optional stable client id"
            ],
            [
              "socket.reconnectMs",
              "Int",
              "1000",
              "Reconnect interval"
            ],
            [
              "screenshot",
              "function",
              "-",
              "Optional screenshot function that returns PNG base64"
            ]
          ]
        }
      ]
    },
    {
      "id": "mcp",
      "name": "@uicheck/mcp",
      "version": "0.1.8",
      "description": "MCP server that communicates with uicheck clients over WebSocket",
      "install": "npx @uicheck/mcp",
      "source": "packages/mcp",
      "readmeUrl": "https://github.com/uicheck/uicheck/blob/main/packages/mcp/README.md",
      "blocks": [
        {
          "type": "paragraph",
          "text": "Local MCP server for uicheck clients. Runtime clients connect to this server through WebSocket, and AI agents call MCP tools to request screenshots and tree-shaped element info from Web, Taro, React Native, Flutter, Apple native, or Android native apps."
        },
        {
          "type": "heading",
          "level": 2,
          "text": "Start"
        },
        {
          "type": "code",
          "lang": "sh",
          "code": "npx @uicheck/mcp"
        },
        {
          "type": "paragraph",
          "text": "Default endpoints:"
        },
        {
          "type": "code",
          "lang": "txt",
          "code": "MCP:    http://127.0.0.1:17322/mcp\nSocket: ws://127.0.0.1:17322/socket"
        },
        {
          "type": "heading",
          "level": 2,
          "text": "AI Client Setup"
        },
        {
          "type": "paragraph",
          "text": "Add the MCP endpoint to any MCP-capable AI client:"
        },
        {
          "type": "code",
          "lang": "json",
          "code": "{\n  \"mcpServers\": {\n    \"uicheck\": {\n      \"url\": \"http://127.0.0.1:17322/mcp\"\n    }\n  }\n}"
        },
        {
          "type": "heading",
          "level": 2,
          "text": "Runtime Clients"
        },
        {
          "type": "paragraph",
          "text": "Connect the app runtime to the socket URL. Browser pages use @uicheck/web:"
        },
        {
          "type": "code",
          "lang": "ts",
          "code": "initUiCheck({\n  socket: {\n    url: 'ws://127.0.0.1:17322/socket'\n  }\n})"
        },
        {
          "type": "paragraph",
          "text": "Use @uicheck/taro for Taro Mini Program pages, @uicheck/rn for React Native screens, uicheck_flutter for Flutter apps, uicheck_apple for Apple native apps, and uicheck_android for Android native apps."
        },
        {
          "type": "heading",
          "level": 2,
          "text": "MCP Tools"
        },
        {
          "type": "table",
          "headers": [
            "Tool",
            "Description",
            "Parameters",
            "Returns"
          ],
          "rows": [
            [
              "list_clients",
              "Lists connected uicheck runtime clients.",
              "None",
              "JSON text array. Each item includes id, connectedAt, lastSeenAt, plus optional userAgent and viewport."
            ],
            [
              "capture_page",
              "Asks a connected runtime to return a PNG screenshot.",
              "clientId optional target client id; timeoutMs MCP wait timeout; waitMs extra wait before capture; captureTimeoutMs runtime screenshot timeout; forceHtml2Canvas forces the Web client to use html2canvas.",
              "MCP image content with image/png; plus JSON text { width, height }."
            ],
            [
              "capture_element",
              "Captures a PNG screenshot of the first element matching the query.",
              "Same capture parameters as capture_page; plus includeHidden, query, selector, styleName with optional styleValue, styles, id, testId, text, accessibilityLabel, className, role, and tag.",
              "MCP image content with image/png; plus JSON text { width, height }."
            ],
            [
              "compare_screenshot",
              "Captures the current page or a matching element and compares it with a provided PNG.",
              "Same capture and search parameters as capture_element; target is page or element, default page; expectedImageBase64 is required; threshold is the pixelmatch threshold.",
              "JSON text with width, height, mismatchedPixels, totalPixels, mismatchRatio, and passed; plus a PNG diff image."
            ],
            [
              "inspect_elements",
              "Returns tree-shaped nodes, text, layout boxes, and metadata. When search parameters are provided, the result keeps only matching nodes and their parent tree.",
              "clientId optional target client id; timeoutMs MCP wait timeout; limit maximum nodes, default 80; includeHidden includes hidden or zero-size nodes; query searches common node fields; selector, styleName plus optional styleValue, styles, id, testId, text, accessibilityLabel, className, role, and tag narrow matches.",
              "JSON text. Includes count and tree-shaped tree; nodes include runtime-provided text, visibility, layout boxes, test IDs, accessibility labels, classes, and children."
            ]
          ]
        },
        {
          "type": "heading",
          "level": 2,
          "text": "CLI"
        },
        {
          "type": "code",
          "lang": "sh",
          "code": "npx @uicheck/mcp -- --host 127.0.0.1 --port 17322"
        }
      ]
    }
  ]
} satisfies Record<GeneratedLocale, GeneratedPackageDoc[]>
