// This file is generated by packages/site/scripts/generate-docs.mjs.
// Do not edit by hand.

export type GeneratedDocBlock =
  | { type: 'heading'; level: number; text: string }
  | { type: 'paragraph'; text: string }
  | { type: 'code'; lang: string; code: string }
  | { type: 'list'; items: string[] }
  | { type: 'table'; headers: string[]; rows: string[][] }

export interface GeneratedPackageDoc {
  id: string
  name: string
  version: string
  description: string
  install: string
  source: string
  readmeUrl: string
  blocks: GeneratedDocBlock[]
}

export type GeneratedLocale = ["zh-CN","en"][number]

export const generatedDocsByLocale = {
  "zh-CN": [
    {
      "id": "web",
      "name": "@uicheck/web",
      "version": "0.1.4",
      "description": "浏览器 DOM 页面客户端",
      "install": "npm install @uicheck/web html2canvas",
      "source": "packages/web",
      "readmeUrl": "https://github.com/uicheck/uicheck/blob/main/packages/web/README.zh-CN.md",
      "blocks": [
        {
          "type": "paragraph",
          "text": "浏览器运行环境客户端。它通过 WebSocket 把真实 DOM 页面连接到 @uicheck/mcp，让 AI 可以通过 MCP 工具读取截图、元素元数据、布局盒和坐标。"
        },
        {
          "type": "heading",
          "level": 2,
          "text": "使用"
        },
        {
          "type": "code",
          "lang": "ts",
          "code": "import html2canvas from 'html2canvas'\nimport { installUiCheck } from '@uicheck/web'\n\ninstallUiCheck(html2canvas, {\n  socket: {\n    url: 'ws://127.0.0.1:17322/socket'\n  }\n})"
        },
        {
          "type": "heading",
          "level": 2,
          "text": "选项"
        },
        {
          "type": "table",
          "headers": [
            "选项",
            "类型",
            "默认值",
            "说明"
          ],
          "rows": [
            [
              "socket.url",
              "string",
              "-",
              "@uicheck/mcp WebSocket 地址"
            ],
            [
              "socket.clientId",
              "string",
              "-",
              "可选的稳定客户端 ID"
            ],
            [
              "socket.reconnectMs",
              "number",
              "1000",
              "断线重连间隔"
            ]
          ]
        }
      ]
    },
    {
      "id": "taro",
      "name": "@uicheck/taro",
      "version": "0.1.4",
      "description": "Taro 小程序页面客户端",
      "install": "npm install @uicheck/taro",
      "source": "packages/taro",
      "readmeUrl": "https://github.com/uicheck/uicheck/blob/main/packages/taro/README.zh-CN.md",
      "blocks": [
        {
          "type": "paragraph",
          "text": "Taro 小程序侧 UI 检查客户端。它通过小程序 selector query 读取页面元素，并连接 @uicheck/mcp 给 AI 提供结构化 UI 信息。"
        },
        {
          "type": "code",
          "lang": "ts",
          "code": "import Taro from '@tarojs/taro'\nimport { installTaroUiCheck } from '@uicheck/taro'\n\ninstallTaroUiCheck(Taro, {\n  socket: {\n    url: 'ws://127.0.0.1:17322/socket'\n  }\n})"
        }
      ]
    },
    {
      "id": "rn",
      "name": "@uicheck/rn",
      "version": "0.1.4",
      "description": "React Native 页面客户端",
      "install": "npm install @uicheck/rn",
      "source": "packages/rn",
      "readmeUrl": "https://github.com/uicheck/uicheck/blob/main/packages/rn/README.zh-CN.md",
      "blocks": [
        {
          "type": "paragraph",
          "text": "React Native 侧 UI 检查客户端。RN 没有 DOM 查询能力，因此需要把希望 AI 看到的组件 ref 注册给 uicheck；注册后 @uicheck/mcp 可以读取元素坐标、文本、testID 和 accessibilityLabel。"
        },
        {
          "type": "code",
          "lang": "ts",
          "code": "import { AppState, Dimensions, Platform } from 'react-native'\nimport {\n  installReactNativeUiCheck,\n  registerReactNativeUiCheckElement\n} from '@uicheck/rn'\n\ninstallReactNativeUiCheck(\n  { AppState, Dimensions, Platform, WebSocket },\n  {\n    route: 'Home',\n    socket: {\n      url: 'ws://127.0.0.1:17322/socket'\n    }\n  }\n)\n\nconst unregister = registerReactNativeUiCheckElement({\n  ref: submitButtonRef,\n  tag: 'Pressable',\n  testID: 'submit-button',\n  text: '提交'\n})"
        },
        {
          "type": "heading",
          "level": 2,
          "text": "截图"
        },
        {
          "type": "paragraph",
          "text": "RN 截图依赖宿主应用能力。需要使用 capture_page 时传入 screenshot 方法并返回 PNG base64。"
        },
        {
          "type": "code",
          "lang": "ts",
          "code": "installReactNativeUiCheck(reactNative, {\n  screenshot: async () => ({\n    mimeType: 'image/png',\n    base64: await captureAppAsBase64()\n  })\n})"
        }
      ]
    },
    {
      "id": "mcp",
      "name": "@uicheck/mcp",
      "version": "0.1.4",
      "description": "通过 WebSocket 连接 uicheck 客户端的 MCP 服务",
      "install": "npm install -g @uicheck/mcp",
      "source": "packages/mcp",
      "readmeUrl": "https://github.com/uicheck/uicheck/blob/main/packages/mcp/README.zh-CN.md",
      "blocks": [
        {
          "type": "paragraph",
          "text": "本地 MCP 服务，用于通过 WebSocket 连接 uicheck 运行环境客户端。浏览器、Taro 小程序或 React Native 应用连接后，AI 可以调用 MCP 工具请求截图和元素信息。"
        },
        {
          "type": "heading",
          "level": 2,
          "text": "启动"
        },
        {
          "type": "code",
          "lang": "sh",
          "code": "npm install -g @uicheck/mcp\nuicheck-mcp"
        },
        {
          "type": "paragraph",
          "text": "默认端点："
        },
        {
          "type": "code",
          "lang": "txt",
          "code": "MCP:    http://127.0.0.1:17322/mcp\nSocket: ws://127.0.0.1:17322/socket"
        },
        {
          "type": "heading",
          "level": 2,
          "text": "AI 客户端配置"
        },
        {
          "type": "paragraph",
          "text": "把 MCP endpoint 配到任意支持 MCP 的 AI 客户端："
        },
        {
          "type": "code",
          "lang": "json",
          "code": "{\n  \"mcpServers\": {\n    \"uicheck\": {\n      \"url\": \"http://127.0.0.1:17322/mcp\"\n    }\n  }\n}"
        },
        {
          "type": "heading",
          "level": 2,
          "text": "运行环境客户端"
        },
        {
          "type": "paragraph",
          "text": "应用运行环境连接 socket 地址。浏览器页面使用 @uicheck/web："
        },
        {
          "type": "code",
          "lang": "ts",
          "code": "installUiCheck(html2canvas, {\n  socket: {\n    url: 'ws://127.0.0.1:17322/socket'\n  }\n})"
        },
        {
          "type": "paragraph",
          "text": "Taro 小程序使用 @uicheck/taro，React Native 使用 @uicheck/rn。"
        },
        {
          "type": "heading",
          "level": 2,
          "text": "MCP 工具"
        },
        {
          "type": "table",
          "headers": [
            "工具",
            "说明"
          ],
          "rows": [
            [
              "list_clients",
              "查看已连接的 uicheck 运行环境客户端。"
            ],
            [
              "capture_page",
              "请求已连接运行环境返回 PNG 截图。"
            ],
            [
              "inspect_elements",
              "返回可见选择器或已注册组件、文本、布局盒和元数据。"
            ],
            [
              "get_element_at_point",
              "返回视口坐标处的元素。"
            ]
          ]
        },
        {
          "type": "heading",
          "level": 2,
          "text": "CLI"
        },
        {
          "type": "code",
          "lang": "sh",
          "code": "uicheck-mcp --host 127.0.0.1 --port 17322"
        }
      ]
    },
    {
      "id": "core",
      "name": "@uicheck/core",
      "version": "0.1.4",
      "description": "uicheck 客户端共享协议 runtime 和类型",
      "install": "npm install @uicheck/core",
      "source": "packages/core",
      "readmeUrl": "https://github.com/uicheck/uicheck/blob/main/packages/core/README.zh-CN.md",
      "blocks": [
        {
          "type": "paragraph",
          "text": "uicheck 平台客户端共享的协议 runtime 和类型。"
        },
        {
          "type": "paragraph",
          "text": "平台包："
        },
        {
          "type": "list",
          "items": [
            "@uicheck/web 用于浏览器 DOM 页面",
            "@uicheck/taro 用于 Taro 小程序页面"
          ]
        }
      ]
    }
  ],
  "en": [
    {
      "id": "web",
      "name": "@uicheck/web",
      "version": "0.1.4",
      "description": "Browser DOM client for uicheck",
      "install": "npm install @uicheck/web html2canvas",
      "source": "packages/web",
      "readmeUrl": "https://github.com/uicheck/uicheck/blob/main/packages/web/README.md",
      "blocks": [
        {
          "type": "paragraph",
          "text": "Browser runtime client for UI Check. It connects a live DOM page to @uicheck/mcp over WebSocket so AI agents can request screenshots, element metadata, layout boxes, and coordinates through MCP tools."
        },
        {
          "type": "heading",
          "level": 2,
          "text": "Usage"
        },
        {
          "type": "code",
          "lang": "ts",
          "code": "import html2canvas from 'html2canvas'\nimport { installUiCheck } from '@uicheck/web'\n\ninstallUiCheck(html2canvas, {\n  socket: {\n    url: 'ws://127.0.0.1:17322/socket'\n  }\n})"
        },
        {
          "type": "heading",
          "level": 2,
          "text": "Options"
        },
        {
          "type": "table",
          "headers": [
            "Option",
            "Type",
            "Default",
            "Description"
          ],
          "rows": [
            [
              "socket.url",
              "string",
              "-",
              "@uicheck/mcp WebSocket URL"
            ],
            [
              "socket.clientId",
              "string",
              "-",
              "Optional stable client id"
            ],
            [
              "socket.reconnectMs",
              "number",
              "1000",
              "Reconnect interval"
            ]
          ]
        }
      ]
    },
    {
      "id": "taro",
      "name": "@uicheck/taro",
      "version": "0.1.4",
      "description": "Taro Mini Program client for uicheck",
      "install": "npm install @uicheck/taro",
      "source": "packages/taro",
      "readmeUrl": "https://github.com/uicheck/uicheck/blob/main/packages/taro/README.md",
      "blocks": [
        {
          "type": "paragraph",
          "text": "Taro Mini Program client for uicheck."
        },
        {
          "type": "code",
          "lang": "ts",
          "code": "import Taro from '@tarojs/taro'\nimport { installTaroUiCheck } from '@uicheck/taro'\n\ninstallTaroUiCheck(Taro, {\n  socket: {\n    url: 'ws://127.0.0.1:17322/socket'\n  }\n})"
        }
      ]
    },
    {
      "id": "rn",
      "name": "@uicheck/rn",
      "version": "0.1.4",
      "description": "React Native client for uicheck",
      "install": "npm install @uicheck/rn",
      "source": "packages/rn",
      "readmeUrl": "https://github.com/uicheck/uicheck/blob/main/packages/rn/README.md",
      "blocks": [
        {
          "type": "paragraph",
          "text": "React Native client for uicheck. React Native does not expose DOM-style queries, so the app registers refs for components that AI should inspect. Once registered, @uicheck/mcp can read element boxes, text, testID, and accessibilityLabel."
        },
        {
          "type": "code",
          "lang": "ts",
          "code": "import { AppState, Dimensions, Platform } from 'react-native'\nimport {\n  installReactNativeUiCheck,\n  registerReactNativeUiCheckElement\n} from '@uicheck/rn'\n\ninstallReactNativeUiCheck(\n  { AppState, Dimensions, Platform, WebSocket },\n  {\n    route: 'Home',\n    socket: {\n      url: 'ws://127.0.0.1:17322/socket'\n    }\n  }\n)\n\nconst unregister = registerReactNativeUiCheckElement({\n  ref: submitButtonRef,\n  tag: 'Pressable',\n  testID: 'submit-button',\n  text: 'Submit'\n})"
        },
        {
          "type": "heading",
          "level": 2,
          "text": "Screenshot"
        },
        {
          "type": "paragraph",
          "text": "React Native screenshots depend on the host app. To support capture_page, pass a screenshot function that returns PNG base64."
        },
        {
          "type": "code",
          "lang": "ts",
          "code": "installReactNativeUiCheck(reactNative, {\n  screenshot: async () => ({\n    mimeType: 'image/png',\n    base64: await captureAppAsBase64()\n  })\n})"
        }
      ]
    },
    {
      "id": "mcp",
      "name": "@uicheck/mcp",
      "version": "0.1.4",
      "description": "MCP server that communicates with uicheck clients over WebSocket",
      "install": "npm install -g @uicheck/mcp",
      "source": "packages/mcp",
      "readmeUrl": "https://github.com/uicheck/uicheck/blob/main/packages/mcp/README.md",
      "blocks": [
        {
          "type": "paragraph",
          "text": "Local MCP server for uicheck clients. Runtime clients connect to this server through WebSocket, and AI agents call MCP tools to request screenshots and element info from browser, Taro, or React Native apps."
        },
        {
          "type": "heading",
          "level": 2,
          "text": "Start"
        },
        {
          "type": "code",
          "lang": "sh",
          "code": "npm install -g @uicheck/mcp\nuicheck-mcp"
        },
        {
          "type": "paragraph",
          "text": "Default endpoints:"
        },
        {
          "type": "code",
          "lang": "txt",
          "code": "MCP:    http://127.0.0.1:17322/mcp\nSocket: ws://127.0.0.1:17322/socket"
        },
        {
          "type": "heading",
          "level": 2,
          "text": "AI Client Setup"
        },
        {
          "type": "paragraph",
          "text": "Add the MCP endpoint to any MCP-capable AI client:"
        },
        {
          "type": "code",
          "lang": "json",
          "code": "{\n  \"mcpServers\": {\n    \"uicheck\": {\n      \"url\": \"http://127.0.0.1:17322/mcp\"\n    }\n  }\n}"
        },
        {
          "type": "heading",
          "level": 2,
          "text": "Runtime Clients"
        },
        {
          "type": "paragraph",
          "text": "Connect the app runtime to the socket URL. Browser pages use @uicheck/web:"
        },
        {
          "type": "code",
          "lang": "ts",
          "code": "installUiCheck(html2canvas, {\n  socket: {\n    url: 'ws://127.0.0.1:17322/socket'\n  }\n})"
        },
        {
          "type": "paragraph",
          "text": "Use @uicheck/taro for Taro Mini Program pages and @uicheck/rn for React Native screens."
        },
        {
          "type": "heading",
          "level": 2,
          "text": "MCP Tools"
        },
        {
          "type": "table",
          "headers": [
            "Tool",
            "Description"
          ],
          "rows": [
            [
              "list_clients",
              "Lists connected uicheck runtime clients."
            ],
            [
              "capture_page",
              "Asks a connected runtime to return a PNG screenshot."
            ],
            [
              "inspect_elements",
              "Returns visible selectors or registered components, text, layout boxes, and metadata."
            ],
            [
              "get_element_at_point",
              "Returns the element at viewport coordinates."
            ]
          ]
        },
        {
          "type": "heading",
          "level": 2,
          "text": "CLI"
        },
        {
          "type": "code",
          "lang": "sh",
          "code": "uicheck-mcp --host 127.0.0.1 --port 17322"
        }
      ]
    },
    {
      "id": "core",
      "name": "@uicheck/core",
      "version": "0.1.4",
      "description": "Shared protocol runtime and types for uicheck clients",
      "install": "npm install @uicheck/core",
      "source": "packages/core",
      "readmeUrl": "https://github.com/uicheck/uicheck/blob/main/packages/core/README.md",
      "blocks": [
        {
          "type": "paragraph",
          "text": "Shared protocol runtime and types for uicheck platform clients."
        },
        {
          "type": "paragraph",
          "text": "Platform packages:"
        },
        {
          "type": "list",
          "items": [
            "@uicheck/web for browser DOM pages",
            "@uicheck/taro for Taro Mini Program pages"
          ]
        }
      ]
    }
  ]
} satisfies Record<GeneratedLocale, GeneratedPackageDoc[]>
