// This file is generated by packages/site/scripts/generate-docs.mjs.
// Do not edit by hand.

export type GeneratedDocBlock =
  | { type: 'heading'; level: number; text: string }
  | { type: 'paragraph'; text: string }
  | { type: 'code'; lang: string; code: string }
  | { type: 'list'; items: string[] }
  | { type: 'table'; headers: string[]; rows: string[][] }

export interface GeneratedPackageDoc {
  id: string
  name: string
  version: string
  description: string
  install: string
  source: string
  readmeUrl: string
  blocks: GeneratedDocBlock[]
}

export type GeneratedLocale = ["zh-CN","en"][number]

export const generatedDocsByLocale = {
  "zh-CN": [
    {
      "id": "web",
      "name": "@uicheck/web",
      "version": "0.1.4",
      "description": "浏览器 DOM 页面客户端",
      "install": "npm install @uicheck/web html2canvas",
      "source": "packages/web",
      "readmeUrl": "https://github.com/uicheck/uicheck/blob/main/packages/web/README.zh-CN.md",
      "blocks": [
        {
          "type": "paragraph",
          "text": "浏览器运行环境客户端。它通过 WebSocket 把真实 DOM 页面连接到 @uicheck/mcp，让 AI 可以通过 MCP 工具读取截图、元素元数据、布局盒和坐标。"
        },
        {
          "type": "heading",
          "level": 2,
          "text": "使用"
        },
        {
          "type": "code",
          "lang": "ts",
          "code": "import html2canvas from 'html2canvas'\nimport { installUiCheck } from '@uicheck/web'\n\ninstallUiCheck(html2canvas, {\n  socket: {\n    url: 'ws://127.0.0.1:17322/socket'\n  }\n})"
        },
        {
          "type": "heading",
          "level": 2,
          "text": "选项"
        },
        {
          "type": "table",
          "headers": [
            "选项",
            "类型",
            "默认值",
            "说明"
          ],
          "rows": [
            [
              "socket.url",
              "string",
              "-",
              "@uicheck/mcp WebSocket 地址"
            ],
            [
              "socket.clientId",
              "string",
              "-",
              "可选的稳定客户端 ID"
            ],
            [
              "socket.reconnectMs",
              "number",
              "1000",
              "断线重连间隔"
            ]
          ]
        }
      ]
    },
    {
      "id": "taro",
      "name": "@uicheck/taro",
      "version": "0.1.4",
      "description": "Taro 小程序页面客户端",
      "install": "npm install @uicheck/taro",
      "source": "packages/taro",
      "readmeUrl": "https://github.com/uicheck/uicheck/blob/main/packages/taro/README.zh-CN.md",
      "blocks": [
        {
          "type": "paragraph",
          "text": "Taro 小程序侧 UI 检查客户端。它通过小程序 selector query 读取页面元素，并连接 @uicheck/mcp 给 AI 提供结构化 UI 信息。"
        },
        {
          "type": "code",
          "lang": "ts",
          "code": "import Taro from '@tarojs/taro'\nimport { installTaroUiCheck } from '@uicheck/taro'\n\ninstallTaroUiCheck(Taro, {\n  socket: {\n    url: 'ws://127.0.0.1:17322/socket'\n  }\n})"
        }
      ]
    },
    {
      "id": "rn",
      "name": "@uicheck/rn",
      "version": "0.1.4",
      "description": "React Native 页面客户端",
      "install": "npm install @uicheck/rn",
      "source": "packages/rn",
      "readmeUrl": "https://github.com/uicheck/uicheck/blob/main/packages/rn/README.zh-CN.md",
      "blocks": [
        {
          "type": "paragraph",
          "text": "React Native 侧 UI 检查客户端。RN 没有 DOM 查询能力，因此需要把希望 AI 看到的组件 ref 注册给 uicheck；注册后 @uicheck/mcp 可以读取元素坐标、文本、testID 和 accessibilityLabel。"
        },
        {
          "type": "code",
          "lang": "ts",
          "code": "import { AppState, Dimensions, Platform } from 'react-native'\nimport {\n  installReactNativeUiCheck,\n  registerReactNativeUiCheckElement\n} from '@uicheck/rn'\n\ninstallReactNativeUiCheck(\n  { AppState, Dimensions, Platform, WebSocket },\n  {\n    route: 'Home',\n    socket: {\n      url: 'ws://127.0.0.1:17322/socket'\n    }\n  }\n)\n\nconst unregister = registerReactNativeUiCheckElement({\n  ref: submitButtonRef,\n  tag: 'Pressable',\n  testID: 'submit-button',\n  text: '提交'\n})"
        },
        {
          "type": "heading",
          "level": 2,
          "text": "截图"
        },
        {
          "type": "paragraph",
          "text": "RN 截图依赖宿主应用能力。需要使用 capture_page 时传入 screenshot 方法并返回 PNG base64。"
        },
        {
          "type": "code",
          "lang": "ts",
          "code": "installReactNativeUiCheck(reactNative, {\n  screenshot: async () => ({\n    mimeType: 'image/png',\n    base64: await captureAppAsBase64()\n  })\n})"
        }
      ]
    },
    {
      "id": "flutter",
      "name": "uicheck_flutter",
      "version": "0.1.4",
      "description": "Flutter 应用运行环境客户端",
      "install": "flutter pub add uicheck_flutter",
      "source": "packages/flutter",
      "readmeUrl": "https://github.com/uicheck/uicheck/blob/main/packages/flutter/README.zh-CN.md",
      "blocks": [
        {
          "type": "paragraph",
          "text": "Flutter 运行环境客户端。它通过 WebSocket 把正在运行的 Flutter 应用连接到 @uicheck/mcp，让 AI 可以通过 MCP 工具读取截图、已注册组件元数据、布局盒和坐标。"
        },
        {
          "type": "heading",
          "level": 2,
          "text": "使用"
        },
        {
          "type": "paragraph",
          "text": "添加包："
        },
        {
          "type": "code",
          "lang": "sh",
          "code": "flutter pub add uicheck_flutter"
        },
        {
          "type": "paragraph",
          "text": "单独启动 MCP 服务："
        },
        {
          "type": "code",
          "lang": "sh",
          "code": "npm install -g @uicheck/mcp\nuicheck-mcp"
        },
        {
          "type": "paragraph",
          "text": "在应用启动附近安装 Flutter 客户端："
        },
        {
          "type": "code",
          "lang": "dart",
          "code": "import 'package:flutter/widgets.dart';\nimport 'package:uicheck_flutter/uicheck_flutter.dart';\n\nfinal uicheckClient = installFlutterUiCheck(\n  options: UiCheckFlutterOptions(\n    title: 'Demo',\n    route: '/home',\n    socket: UiCheckSocketOptions(\n      url: 'ws://127.0.0.1:17322/socket',\n      clientId: 'flutter-demo',\n    ),\n    screenshot: (params) => captureRepaintBoundaryAsPng(\n      repaintBoundaryKey: appBoundaryKey,\n      title: 'Demo',\n      url: '/home',\n    ),\n  ),\n);"
        },
        {
          "type": "paragraph",
          "text": "注册 AI 需要查看的组件："
        },
        {
          "type": "code",
          "lang": "dart",
          "code": "final submitButtonKey = GlobalKey();\n\nfinal unregister = registerFlutterUiCheckElement(\n  UiCheckFlutterElementRegistration(\n    key: submitButtonKey,\n    tag: 'ElevatedButton',\n    testID: 'submit-button',\n    text: '提交',\n  ),\n);"
        },
        {
          "type": "paragraph",
          "text": "使用截图 helper 时，把 app 或页面包在 RepaintBoundary 中："
        },
        {
          "type": "code",
          "lang": "dart",
          "code": "final appBoundaryKey = GlobalKey();\n\nRepaintBoundary(\n  key: appBoundaryKey,\n  child: MyApp(),\n);"
        },
        {
          "type": "paragraph",
          "text": "不再使用时释放客户端和注册回调："
        },
        {
          "type": "code",
          "lang": "dart",
          "code": "unregister();\nuicheckClient.dispose();"
        },
        {
          "type": "heading",
          "level": 2,
          "text": "MCP 工具"
        },
        {
          "type": "table",
          "headers": [
            "工具",
            "说明"
          ],
          "rows": [
            [
              "capture_page",
              "调用配置的截图回调返回 PNG 截图。"
            ],
            [
              "inspect_elements",
              "返回已注册组件的元数据、文本、布局盒和可见状态。"
            ],
            [
              "get_element_at_point",
              "返回视口坐标处最小的已注册组件。"
            ]
          ]
        },
        {
          "type": "heading",
          "level": 2,
          "text": "说明"
        },
        {
          "type": "paragraph",
          "text": "Flutter 没有 DOM 查询 API。需要用 GlobalKey 注册 AI 需要检查的组件，客户端会通过 RenderBox.localToGlobal 读取组件位置。"
        }
      ]
    },
    {
      "id": "android",
      "name": "uicheck_android",
      "version": "0.1.4",
      "description": "Android 原生应用运行环境客户端",
      "install": "Android library: https://github.com/uicheck/uicheck, path packages/android",
      "source": "packages/android",
      "readmeUrl": "https://github.com/uicheck/uicheck/blob/main/packages/android/README.zh-CN.md",
      "blocks": [
        {
          "type": "paragraph",
          "text": "UI Check 的 Android 原生运行环境客户端。它通过 WebSocket 连接 @uicheck/mcp，让 AI Agent 可以通过 MCP 工具读取截图、已注册原生 View 信息、布局盒子和坐标。"
        },
        {
          "type": "heading",
          "level": 2,
          "text": "安装"
        },
        {
          "type": "paragraph",
          "text": "把这个仓库作为 Android library 依赖加入项目："
        },
        {
          "type": "code",
          "lang": "txt",
          "code": "https://github.com/uicheck/uicheck"
        },
        {
          "type": "paragraph",
          "text": "包路径："
        },
        {
          "type": "code",
          "lang": "txt",
          "code": "packages/android"
        },
        {
          "type": "paragraph",
          "text": "单独启动 MCP 服务："
        },
        {
          "type": "code",
          "lang": "sh",
          "code": "npm install -g @uicheck/mcp\nuicheck-mcp"
        },
        {
          "type": "heading",
          "level": 2,
          "text": "使用"
        },
        {
          "type": "paragraph",
          "text": "在应用启动附近安装客户端："
        },
        {
          "type": "code",
          "lang": "kotlin",
          "code": "import ai.uicheck.android.UiCheckAndroidOptions\nimport ai.uicheck.android.UiCheckAndroidSocketOptions\nimport ai.uicheck.android.UiCheckAndroidViewportInfo\nimport ai.uicheck.android.createAndroidViewScreenshotProvider\nimport ai.uicheck.android.installAndroidUiCheck\n\nval client = installAndroidUiCheck(\n  UiCheckAndroidOptions(\n    socket = UiCheckAndroidSocketOptions(\n      url = \"ws://127.0.0.1:17322/socket\",\n      clientId = \"android-demo\"\n    ),\n    title = \"Demo\",\n    route = \"/home\",\n    platform = \"android\",\n    viewport = {\n      UiCheckAndroidViewportInfo(width = 393, height = 873, devicePixelRatio = 2.75)\n    },\n    screenshot = createAndroidViewScreenshotProvider(rootView)\n  )\n)"
        },
        {
          "type": "paragraph",
          "text": "注册希望 AI 检查的 View："
        },
        {
          "type": "code",
          "lang": "kotlin",
          "code": "import ai.uicheck.android.registerAndroidUiCheckView\n\nval unregister = registerAndroidUiCheckView(\n  submitButton,\n  tag = \"Button\",\n  testID = \"submit-button\",\n  text = \"Submit\"\n)"
        },
        {
          "type": "paragraph",
          "text": "如果是 Compose 或非 View 抽象，也可以注册自定义 frame provider："
        },
        {
          "type": "code",
          "lang": "kotlin",
          "code": "import ai.uicheck.android.UiCheckAndroidElementRegistration\nimport ai.uicheck.android.UiCheckAndroidRect\nimport ai.uicheck.android.registerAndroidUiCheckElement\n\nval unregister = registerAndroidUiCheckElement(\n  UiCheckAndroidElementRegistration(\n    tag = \"Button\",\n    testID = \"submit-button\",\n    text = \"Submit\",\n    frame = { UiCheckAndroidRect(12.0, 24.0, 120.0, 48.0) }\n  )\n)"
        },
        {
          "type": "paragraph",
          "text": "不用时释放："
        },
        {
          "type": "code",
          "lang": "kotlin",
          "code": "unregister()\nclient.close()"
        },
        {
          "type": "heading",
          "level": 2,
          "text": "MCP 工具"
        },
        {
          "type": "table",
          "headers": [
            "工具",
            "说明"
          ],
          "rows": [
            [
              "capture_page",
              "使用配置的截图 provider 返回 PNG 截图。"
            ],
            [
              "inspect_elements",
              "返回已注册原生 View 的元数据、文本、布局盒子和可见状态。"
            ],
            [
              "get_element_at_point",
              "返回视口坐标下最小的已注册 View。"
            ]
          ]
        },
        {
          "type": "heading",
          "level": 2,
          "text": "说明"
        },
        {
          "type": "paragraph",
          "text": "Android 原生应用没有 DOM 查询 API。需要注册 AI 要检查的 View 或组件。registerAndroidUiCheckView 会用屏幕坐标测量原生 View。"
        }
      ]
    },
    {
      "id": "apple",
      "name": "uicheck_apple",
      "version": "0.1.4",
      "description": "Apple 原生应用运行环境客户端",
      "install": "Swift Package: https://github.com/uicheck/uicheck, product UICheckApple",
      "source": "packages/apple",
      "readmeUrl": "https://github.com/uicheck/uicheck/blob/main/packages/apple/README.zh-CN.md",
      "blocks": [
        {
          "type": "paragraph",
          "text": "Apple 原生运行环境客户端。它通过 WebSocket 把 iOS、macOS、tvOS 或 visionOS 应用连接到 @uicheck/mcp，让 AI 可以通过 MCP 工具读取截图、已注册原生视图元数据、布局盒和坐标。"
        },
        {
          "type": "heading",
          "level": 2,
          "text": "安装"
        },
        {
          "type": "paragraph",
          "text": "把这个仓库作为 Swift Package 依赖，并选择 UICheckApple product："
        },
        {
          "type": "code",
          "lang": "txt",
          "code": "https://github.com/uicheck/uicheck"
        },
        {
          "type": "paragraph",
          "text": "包路径："
        },
        {
          "type": "code",
          "lang": "txt",
          "code": "packages/apple"
        },
        {
          "type": "paragraph",
          "text": "单独启动 MCP 服务："
        },
        {
          "type": "code",
          "lang": "sh",
          "code": "npm install -g @uicheck/mcp\nuicheck-mcp"
        },
        {
          "type": "heading",
          "level": 2,
          "text": "使用"
        },
        {
          "type": "paragraph",
          "text": "在应用启动附近安装客户端："
        },
        {
          "type": "code",
          "lang": "swift",
          "code": "import UICheckApple\n\nlet client = installAppleUiCheck(\n  options: UiCheckAppleOptions(\n    socket: UiCheckAppleSocketOptions(\n      url: \"ws://127.0.0.1:17322/socket\",\n      clientId: \"ios-demo\"\n    ),\n    title: \"Demo\",\n    route: \"/home\",\n    platform: \"ios\",\n    viewport: {\n      UiCheckAppleViewportInfo(width: 390, height: 844, devicePixelRatio: 3)\n    },\n    screenshot: { params in\n      UiCheckAppleScreenshotResult(\n        title: \"Demo\",\n        width: 390,\n        height: 844,\n        mimeType: \"image/png\",\n        base64: captureAppAsBase64Png()\n      )\n    }\n  )\n)"
        },
        {
          "type": "paragraph",
          "text": "注册 AI 需要查看的视图："
        },
        {
          "type": "code",
          "lang": "swift",
          "code": "let unregister = registerAppleUiCheckView(\n  submitButton,\n  tag: \"UIButton\",\n  testID: \"submit-button\",\n  text: \"提交\"\n)"
        },
        {
          "type": "paragraph",
          "text": "接入 SwiftUI 或非 View 抽象时，也可以注册自定义 frame provider："
        },
        {
          "type": "code",
          "lang": "swift",
          "code": "let unregister = registerAppleUiCheckElement(\n  UiCheckAppleElementRegistration(\n    tag: \"Button\",\n    testID: \"submit-button\",\n    text: \"提交\",\n    frame: { CGRect(x: 12, y: 24, width: 120, height: 44) }\n  )\n)"
        },
        {
          "type": "paragraph",
          "text": "不再使用时释放："
        },
        {
          "type": "code",
          "lang": "swift",
          "code": "unregister()\nclient.close()"
        },
        {
          "type": "heading",
          "level": 2,
          "text": "MCP 工具"
        },
        {
          "type": "table",
          "headers": [
            "工具",
            "说明"
          ],
          "rows": [
            [
              "capture_page",
              "调用配置的截图 provider 返回 PNG 截图。"
            ],
            [
              "inspect_elements",
              "返回已注册原生视图的元数据、文本、布局盒和可见状态。"
            ],
            [
              "get_element_at_point",
              "返回视口坐标处最小的已注册视图。"
            ]
          ]
        },
        {
          "type": "heading",
          "level": 2,
          "text": "说明"
        },
        {
          "type": "paragraph",
          "text": "Apple 原生应用没有 DOM 查询 API。需要注册 AI 需要检查的视图或组件。UIKit 和 AppKit helper 会用窗口坐标测量已注册视图。"
        }
      ]
    },
    {
      "id": "mcp",
      "name": "@uicheck/mcp",
      "version": "0.1.4",
      "description": "通过 WebSocket 连接 uicheck 客户端的 MCP 服务",
      "install": "npm install -g @uicheck/mcp",
      "source": "packages/mcp",
      "readmeUrl": "https://github.com/uicheck/uicheck/blob/main/packages/mcp/README.zh-CN.md",
      "blocks": [
        {
          "type": "paragraph",
          "text": "本地 MCP 服务，用于通过 WebSocket 连接 uicheck 运行环境客户端。浏览器、Taro 小程序或 React Native 应用连接后，AI 可以调用 MCP 工具请求截图和元素信息。"
        },
        {
          "type": "heading",
          "level": 2,
          "text": "启动"
        },
        {
          "type": "code",
          "lang": "sh",
          "code": "npm install -g @uicheck/mcp\nuicheck-mcp"
        },
        {
          "type": "paragraph",
          "text": "默认端点："
        },
        {
          "type": "code",
          "lang": "txt",
          "code": "MCP:    http://127.0.0.1:17322/mcp\nSocket: ws://127.0.0.1:17322/socket"
        },
        {
          "type": "heading",
          "level": 2,
          "text": "AI 客户端配置"
        },
        {
          "type": "paragraph",
          "text": "把 MCP endpoint 配到任意支持 MCP 的 AI 客户端："
        },
        {
          "type": "code",
          "lang": "json",
          "code": "{\n  \"mcpServers\": {\n    \"uicheck\": {\n      \"url\": \"http://127.0.0.1:17322/mcp\"\n    }\n  }\n}"
        },
        {
          "type": "heading",
          "level": 2,
          "text": "运行环境客户端"
        },
        {
          "type": "paragraph",
          "text": "应用运行环境连接 socket 地址。浏览器页面使用 @uicheck/web："
        },
        {
          "type": "code",
          "lang": "ts",
          "code": "installUiCheck(html2canvas, {\n  socket: {\n    url: 'ws://127.0.0.1:17322/socket'\n  }\n})"
        },
        {
          "type": "paragraph",
          "text": "Taro 小程序使用 @uicheck/taro，React Native 使用 @uicheck/rn。"
        },
        {
          "type": "heading",
          "level": 2,
          "text": "MCP 工具"
        },
        {
          "type": "table",
          "headers": [
            "工具",
            "说明"
          ],
          "rows": [
            [
              "list_clients",
              "查看已连接的 uicheck 运行环境客户端。"
            ],
            [
              "capture_page",
              "请求已连接运行环境返回 PNG 截图。"
            ],
            [
              "inspect_elements",
              "返回可见选择器或已注册组件、文本、布局盒和元数据。"
            ],
            [
              "get_element_at_point",
              "返回视口坐标处的元素。"
            ]
          ]
        },
        {
          "type": "heading",
          "level": 2,
          "text": "CLI"
        },
        {
          "type": "code",
          "lang": "sh",
          "code": "uicheck-mcp --host 127.0.0.1 --port 17322"
        }
      ]
    },
    {
      "id": "core",
      "name": "@uicheck/core",
      "version": "0.1.4",
      "description": "uicheck 客户端共享协议 runtime 和类型",
      "install": "npm install @uicheck/core",
      "source": "packages/core",
      "readmeUrl": "https://github.com/uicheck/uicheck/blob/main/packages/core/README.zh-CN.md",
      "blocks": [
        {
          "type": "paragraph",
          "text": "uicheck 平台客户端共享的协议 runtime 和类型。"
        },
        {
          "type": "paragraph",
          "text": "平台包："
        },
        {
          "type": "list",
          "items": [
            "@uicheck/web 用于浏览器 DOM 页面",
            "@uicheck/taro 用于 Taro 小程序页面"
          ]
        }
      ]
    }
  ],
  "en": [
    {
      "id": "web",
      "name": "@uicheck/web",
      "version": "0.1.4",
      "description": "Browser DOM client for uicheck",
      "install": "npm install @uicheck/web html2canvas",
      "source": "packages/web",
      "readmeUrl": "https://github.com/uicheck/uicheck/blob/main/packages/web/README.md",
      "blocks": [
        {
          "type": "paragraph",
          "text": "Browser runtime client for UI Check. It connects a live DOM page to @uicheck/mcp over WebSocket so AI agents can request screenshots, element metadata, layout boxes, and coordinates through MCP tools."
        },
        {
          "type": "heading",
          "level": 2,
          "text": "Usage"
        },
        {
          "type": "code",
          "lang": "ts",
          "code": "import html2canvas from 'html2canvas'\nimport { installUiCheck } from '@uicheck/web'\n\ninstallUiCheck(html2canvas, {\n  socket: {\n    url: 'ws://127.0.0.1:17322/socket'\n  }\n})"
        },
        {
          "type": "heading",
          "level": 2,
          "text": "Options"
        },
        {
          "type": "table",
          "headers": [
            "Option",
            "Type",
            "Default",
            "Description"
          ],
          "rows": [
            [
              "socket.url",
              "string",
              "-",
              "@uicheck/mcp WebSocket URL"
            ],
            [
              "socket.clientId",
              "string",
              "-",
              "Optional stable client id"
            ],
            [
              "socket.reconnectMs",
              "number",
              "1000",
              "Reconnect interval"
            ]
          ]
        }
      ]
    },
    {
      "id": "taro",
      "name": "@uicheck/taro",
      "version": "0.1.4",
      "description": "Taro Mini Program client for uicheck",
      "install": "npm install @uicheck/taro",
      "source": "packages/taro",
      "readmeUrl": "https://github.com/uicheck/uicheck/blob/main/packages/taro/README.md",
      "blocks": [
        {
          "type": "paragraph",
          "text": "Taro Mini Program client for uicheck."
        },
        {
          "type": "code",
          "lang": "ts",
          "code": "import Taro from '@tarojs/taro'\nimport { installTaroUiCheck } from '@uicheck/taro'\n\ninstallTaroUiCheck(Taro, {\n  socket: {\n    url: 'ws://127.0.0.1:17322/socket'\n  }\n})"
        }
      ]
    },
    {
      "id": "rn",
      "name": "@uicheck/rn",
      "version": "0.1.4",
      "description": "React Native client for uicheck",
      "install": "npm install @uicheck/rn",
      "source": "packages/rn",
      "readmeUrl": "https://github.com/uicheck/uicheck/blob/main/packages/rn/README.md",
      "blocks": [
        {
          "type": "paragraph",
          "text": "React Native client for uicheck. React Native does not expose DOM-style queries, so the app registers refs for components that AI should inspect. Once registered, @uicheck/mcp can read element boxes, text, testID, and accessibilityLabel."
        },
        {
          "type": "code",
          "lang": "ts",
          "code": "import { AppState, Dimensions, Platform } from 'react-native'\nimport {\n  installReactNativeUiCheck,\n  registerReactNativeUiCheckElement\n} from '@uicheck/rn'\n\ninstallReactNativeUiCheck(\n  { AppState, Dimensions, Platform, WebSocket },\n  {\n    route: 'Home',\n    socket: {\n      url: 'ws://127.0.0.1:17322/socket'\n    }\n  }\n)\n\nconst unregister = registerReactNativeUiCheckElement({\n  ref: submitButtonRef,\n  tag: 'Pressable',\n  testID: 'submit-button',\n  text: 'Submit'\n})"
        },
        {
          "type": "heading",
          "level": 2,
          "text": "Screenshot"
        },
        {
          "type": "paragraph",
          "text": "React Native screenshots depend on the host app. To support capture_page, pass a screenshot function that returns PNG base64."
        },
        {
          "type": "code",
          "lang": "ts",
          "code": "installReactNativeUiCheck(reactNative, {\n  screenshot: async () => ({\n    mimeType: 'image/png',\n    base64: await captureAppAsBase64()\n  })\n})"
        }
      ]
    },
    {
      "id": "flutter",
      "name": "uicheck_flutter",
      "version": "0.1.4",
      "description": "Flutter runtime client for uicheck",
      "install": "flutter pub add uicheck_flutter",
      "source": "packages/flutter",
      "readmeUrl": "https://github.com/uicheck/uicheck/blob/main/packages/flutter/README.md",
      "blocks": [
        {
          "type": "paragraph",
          "text": "Flutter runtime client for UI Check. It connects a running Flutter app to @uicheck/mcp over WebSocket so AI agents can request screenshots, registered widget metadata, layout boxes, and coordinates through MCP tools."
        },
        {
          "type": "heading",
          "level": 2,
          "text": "Usage"
        },
        {
          "type": "paragraph",
          "text": "Add the package:"
        },
        {
          "type": "code",
          "lang": "sh",
          "code": "flutter pub add uicheck_flutter"
        },
        {
          "type": "paragraph",
          "text": "Start the MCP server separately:"
        },
        {
          "type": "code",
          "lang": "sh",
          "code": "npm install -g @uicheck/mcp\nuicheck-mcp"
        },
        {
          "type": "paragraph",
          "text": "Install the Flutter client near app startup:"
        },
        {
          "type": "code",
          "lang": "dart",
          "code": "import 'package:flutter/widgets.dart';\nimport 'package:uicheck_flutter/uicheck_flutter.dart';\n\nfinal uicheckClient = installFlutterUiCheck(\n  options: UiCheckFlutterOptions(\n    title: 'Demo',\n    route: '/home',\n    socket: UiCheckSocketOptions(\n      url: 'ws://127.0.0.1:17322/socket',\n      clientId: 'flutter-demo',\n    ),\n    screenshot: (params) => captureRepaintBoundaryAsPng(\n      repaintBoundaryKey: appBoundaryKey,\n      title: 'Demo',\n      url: '/home',\n    ),\n  ),\n);"
        },
        {
          "type": "paragraph",
          "text": "Register widgets that AI should inspect:"
        },
        {
          "type": "code",
          "lang": "dart",
          "code": "final submitButtonKey = GlobalKey();\n\nfinal unregister = registerFlutterUiCheckElement(\n  UiCheckFlutterElementRegistration(\n    key: submitButtonKey,\n    tag: 'ElevatedButton',\n    testID: 'submit-button',\n    text: 'Submit',\n  ),\n);"
        },
        {
          "type": "paragraph",
          "text": "Wrap the app or screen in a RepaintBoundary when using the screenshot helper:"
        },
        {
          "type": "code",
          "lang": "dart",
          "code": "final appBoundaryKey = GlobalKey();\n\nRepaintBoundary(\n  key: appBoundaryKey,\n  child: MyApp(),\n);"
        },
        {
          "type": "paragraph",
          "text": "Dispose the client and unregister callbacks when they are no longer needed:"
        },
        {
          "type": "code",
          "lang": "dart",
          "code": "unregister();\nuicheckClient.dispose();"
        },
        {
          "type": "heading",
          "level": 2,
          "text": "MCP Tools"
        },
        {
          "type": "table",
          "headers": [
            "Tool",
            "Description"
          ],
          "rows": [
            [
              "capture_page",
              "Uses the configured screenshot callback to return a PNG screenshot."
            ],
            [
              "inspect_elements",
              "Returns registered widget metadata, text, layout boxes, and visibility."
            ],
            [
              "get_element_at_point",
              "Returns the smallest registered widget at viewport coordinates."
            ]
          ]
        },
        {
          "type": "heading",
          "level": 2,
          "text": "Notes"
        },
        {
          "type": "paragraph",
          "text": "Flutter does not expose a DOM query API. Register the widgets that AI needs to inspect with a GlobalKey. The client measures each registered widget through RenderBox.localToGlobal."
        }
      ]
    },
    {
      "id": "android",
      "name": "uicheck_android",
      "version": "0.1.4",
      "description": "Android native runtime client for uicheck",
      "install": "Android library: https://github.com/uicheck/uicheck, path packages/android",
      "source": "packages/android",
      "readmeUrl": "https://github.com/uicheck/uicheck/blob/main/packages/android/README.md",
      "blocks": [
        {
          "type": "paragraph",
          "text": "Android native runtime client for UI Check. It connects native Android apps to @uicheck/mcp over WebSocket so AI agents can request screenshots, registered view metadata, layout boxes, and coordinates through MCP tools."
        },
        {
          "type": "heading",
          "level": 2,
          "text": "Install"
        },
        {
          "type": "paragraph",
          "text": "Add this repository as an Android library dependency:"
        },
        {
          "type": "code",
          "lang": "txt",
          "code": "https://github.com/uicheck/uicheck"
        },
        {
          "type": "paragraph",
          "text": "Package path:"
        },
        {
          "type": "code",
          "lang": "txt",
          "code": "packages/android"
        },
        {
          "type": "paragraph",
          "text": "Start the MCP server separately:"
        },
        {
          "type": "code",
          "lang": "sh",
          "code": "npm install -g @uicheck/mcp\nuicheck-mcp"
        },
        {
          "type": "heading",
          "level": 2,
          "text": "Usage"
        },
        {
          "type": "paragraph",
          "text": "Install the client near app startup:"
        },
        {
          "type": "code",
          "lang": "kotlin",
          "code": "import ai.uicheck.android.UiCheckAndroidOptions\nimport ai.uicheck.android.UiCheckAndroidSocketOptions\nimport ai.uicheck.android.UiCheckAndroidViewportInfo\nimport ai.uicheck.android.createAndroidViewScreenshotProvider\nimport ai.uicheck.android.installAndroidUiCheck\n\nval client = installAndroidUiCheck(\n  UiCheckAndroidOptions(\n    socket = UiCheckAndroidSocketOptions(\n      url = \"ws://127.0.0.1:17322/socket\",\n      clientId = \"android-demo\"\n    ),\n    title = \"Demo\",\n    route = \"/home\",\n    platform = \"android\",\n    viewport = {\n      UiCheckAndroidViewportInfo(width = 393, height = 873, devicePixelRatio = 2.75)\n    },\n    screenshot = createAndroidViewScreenshotProvider(rootView)\n  )\n)"
        },
        {
          "type": "paragraph",
          "text": "Register views that AI should inspect:"
        },
        {
          "type": "code",
          "lang": "kotlin",
          "code": "import ai.uicheck.android.registerAndroidUiCheckView\n\nval unregister = registerAndroidUiCheckView(\n  submitButton,\n  tag = \"Button\",\n  testID = \"submit-button\",\n  text = \"Submit\"\n)"
        },
        {
          "type": "paragraph",
          "text": "You can also register a custom frame provider for Compose or non-view abstractions:"
        },
        {
          "type": "code",
          "lang": "kotlin",
          "code": "import ai.uicheck.android.UiCheckAndroidElementRegistration\nimport ai.uicheck.android.UiCheckAndroidRect\nimport ai.uicheck.android.registerAndroidUiCheckElement\n\nval unregister = registerAndroidUiCheckElement(\n  UiCheckAndroidElementRegistration(\n    tag = \"Button\",\n    testID = \"submit-button\",\n    text = \"Submit\",\n    frame = { UiCheckAndroidRect(12.0, 24.0, 120.0, 48.0) }\n  )\n)"
        },
        {
          "type": "paragraph",
          "text": "Dispose when no longer needed:"
        },
        {
          "type": "code",
          "lang": "kotlin",
          "code": "unregister()\nclient.close()"
        },
        {
          "type": "heading",
          "level": 2,
          "text": "MCP Tools"
        },
        {
          "type": "table",
          "headers": [
            "Tool",
            "Description"
          ],
          "rows": [
            [
              "capture_page",
              "Uses the configured screenshot provider to return a PNG screenshot."
            ],
            [
              "inspect_elements",
              "Returns registered native view metadata, text, layout boxes, and visibility."
            ],
            [
              "get_element_at_point",
              "Returns the smallest registered view at viewport coordinates."
            ]
          ]
        },
        {
          "type": "heading",
          "level": 2,
          "text": "Notes"
        },
        {
          "type": "paragraph",
          "text": "Android native apps do not expose a DOM query API. Register the views or components that AI needs to inspect. registerAndroidUiCheckView measures native views in screen coordinates."
        }
      ]
    },
    {
      "id": "apple",
      "name": "uicheck_apple",
      "version": "0.1.4",
      "description": "Apple native runtime client for uicheck",
      "install": "Swift Package: https://github.com/uicheck/uicheck, product UICheckApple",
      "source": "packages/apple",
      "readmeUrl": "https://github.com/uicheck/uicheck/blob/main/packages/apple/README.md",
      "blocks": [
        {
          "type": "paragraph",
          "text": "Apple native runtime client for UI Check. It connects iOS, macOS, tvOS, or visionOS apps to @uicheck/mcp over WebSocket so AI agents can request screenshots, registered native view metadata, layout boxes, and coordinates through MCP tools."
        },
        {
          "type": "heading",
          "level": 2,
          "text": "Install"
        },
        {
          "type": "paragraph",
          "text": "Add this repository as a Swift Package dependency and select the UICheckApple product:"
        },
        {
          "type": "code",
          "lang": "txt",
          "code": "https://github.com/uicheck/uicheck"
        },
        {
          "type": "paragraph",
          "text": "Package path:"
        },
        {
          "type": "code",
          "lang": "txt",
          "code": "packages/apple"
        },
        {
          "type": "paragraph",
          "text": "Start the MCP server separately:"
        },
        {
          "type": "code",
          "lang": "sh",
          "code": "npm install -g @uicheck/mcp\nuicheck-mcp"
        },
        {
          "type": "heading",
          "level": 2,
          "text": "Usage"
        },
        {
          "type": "paragraph",
          "text": "Install the client near app startup:"
        },
        {
          "type": "code",
          "lang": "swift",
          "code": "import UICheckApple\n\nlet client = installAppleUiCheck(\n  options: UiCheckAppleOptions(\n    socket: UiCheckAppleSocketOptions(\n      url: \"ws://127.0.0.1:17322/socket\",\n      clientId: \"ios-demo\"\n    ),\n    title: \"Demo\",\n    route: \"/home\",\n    platform: \"ios\",\n    viewport: {\n      UiCheckAppleViewportInfo(width: 390, height: 844, devicePixelRatio: 3)\n    },\n    screenshot: { params in\n      UiCheckAppleScreenshotResult(\n        title: \"Demo\",\n        width: 390,\n        height: 844,\n        mimeType: \"image/png\",\n        base64: captureAppAsBase64Png()\n      )\n    }\n  )\n)"
        },
        {
          "type": "paragraph",
          "text": "Register views that AI should inspect:"
        },
        {
          "type": "code",
          "lang": "swift",
          "code": "let unregister = registerAppleUiCheckView(\n  submitButton,\n  tag: \"UIButton\",\n  testID: \"submit-button\",\n  text: \"Submit\"\n)"
        },
        {
          "type": "paragraph",
          "text": "You can also register a custom frame provider when integrating with SwiftUI or non-view abstractions:"
        },
        {
          "type": "code",
          "lang": "swift",
          "code": "let unregister = registerAppleUiCheckElement(\n  UiCheckAppleElementRegistration(\n    tag: \"Button\",\n    testID: \"submit-button\",\n    text: \"Submit\",\n    frame: { CGRect(x: 12, y: 24, width: 120, height: 44) }\n  )\n)"
        },
        {
          "type": "paragraph",
          "text": "Dispose when no longer needed:"
        },
        {
          "type": "code",
          "lang": "swift",
          "code": "unregister()\nclient.close()"
        },
        {
          "type": "heading",
          "level": 2,
          "text": "MCP Tools"
        },
        {
          "type": "table",
          "headers": [
            "Tool",
            "Description"
          ],
          "rows": [
            [
              "capture_page",
              "Uses the configured screenshot provider to return a PNG screenshot."
            ],
            [
              "inspect_elements",
              "Returns registered native view metadata, text, layout boxes, and visibility."
            ],
            [
              "get_element_at_point",
              "Returns the smallest registered view at viewport coordinates."
            ]
          ]
        },
        {
          "type": "heading",
          "level": 2,
          "text": "Notes"
        },
        {
          "type": "paragraph",
          "text": "Apple native apps do not expose a DOM query API. Register the views or components that AI needs to inspect. UIKit and AppKit helpers measure registered views in window coordinates."
        }
      ]
    },
    {
      "id": "mcp",
      "name": "@uicheck/mcp",
      "version": "0.1.4",
      "description": "MCP server that communicates with uicheck clients over WebSocket",
      "install": "npm install -g @uicheck/mcp",
      "source": "packages/mcp",
      "readmeUrl": "https://github.com/uicheck/uicheck/blob/main/packages/mcp/README.md",
      "blocks": [
        {
          "type": "paragraph",
          "text": "Local MCP server for uicheck clients. Runtime clients connect to this server through WebSocket, and AI agents call MCP tools to request screenshots and element info from browser, Taro, or React Native apps."
        },
        {
          "type": "heading",
          "level": 2,
          "text": "Start"
        },
        {
          "type": "code",
          "lang": "sh",
          "code": "npm install -g @uicheck/mcp\nuicheck-mcp"
        },
        {
          "type": "paragraph",
          "text": "Default endpoints:"
        },
        {
          "type": "code",
          "lang": "txt",
          "code": "MCP:    http://127.0.0.1:17322/mcp\nSocket: ws://127.0.0.1:17322/socket"
        },
        {
          "type": "heading",
          "level": 2,
          "text": "AI Client Setup"
        },
        {
          "type": "paragraph",
          "text": "Add the MCP endpoint to any MCP-capable AI client:"
        },
        {
          "type": "code",
          "lang": "json",
          "code": "{\n  \"mcpServers\": {\n    \"uicheck\": {\n      \"url\": \"http://127.0.0.1:17322/mcp\"\n    }\n  }\n}"
        },
        {
          "type": "heading",
          "level": 2,
          "text": "Runtime Clients"
        },
        {
          "type": "paragraph",
          "text": "Connect the app runtime to the socket URL. Browser pages use @uicheck/web:"
        },
        {
          "type": "code",
          "lang": "ts",
          "code": "installUiCheck(html2canvas, {\n  socket: {\n    url: 'ws://127.0.0.1:17322/socket'\n  }\n})"
        },
        {
          "type": "paragraph",
          "text": "Use @uicheck/taro for Taro Mini Program pages and @uicheck/rn for React Native screens."
        },
        {
          "type": "heading",
          "level": 2,
          "text": "MCP Tools"
        },
        {
          "type": "table",
          "headers": [
            "Tool",
            "Description"
          ],
          "rows": [
            [
              "list_clients",
              "Lists connected uicheck runtime clients."
            ],
            [
              "capture_page",
              "Asks a connected runtime to return a PNG screenshot."
            ],
            [
              "inspect_elements",
              "Returns visible selectors or registered components, text, layout boxes, and metadata."
            ],
            [
              "get_element_at_point",
              "Returns the element at viewport coordinates."
            ]
          ]
        },
        {
          "type": "heading",
          "level": 2,
          "text": "CLI"
        },
        {
          "type": "code",
          "lang": "sh",
          "code": "uicheck-mcp --host 127.0.0.1 --port 17322"
        }
      ]
    },
    {
      "id": "core",
      "name": "@uicheck/core",
      "version": "0.1.4",
      "description": "Shared protocol runtime and types for uicheck clients",
      "install": "npm install @uicheck/core",
      "source": "packages/core",
      "readmeUrl": "https://github.com/uicheck/uicheck/blob/main/packages/core/README.md",
      "blocks": [
        {
          "type": "paragraph",
          "text": "Shared protocol runtime and types for uicheck platform clients."
        },
        {
          "type": "paragraph",
          "text": "Platform packages:"
        },
        {
          "type": "list",
          "items": [
            "@uicheck/web for browser DOM pages",
            "@uicheck/taro for Taro Mini Program pages"
          ]
        }
      ]
    }
  ]
} satisfies Record<GeneratedLocale, GeneratedPackageDoc[]>
